# This is a basic workflow to help you get started with Actions

name: Test Deployment

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [start_deploy]
  
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  node-deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - run: cd /home/ubuntu/hello-world-node/ && git pull origin
     - run:  cd /home/ubuntu/hello-world-node/ && npm install
     - run: cd /home/ubuntu/hello-world-node/ && pm2 restart index.js

